### ISSUE TITLE
About datasets

### ISSUE THREAD

**Issue by dongliangchang** [NUST-Machine-Intelligence-Laboratory/Softly-Update-Drop#2]
Hi, the download link of the three datasets has expired, can you provide a new one? Many thanks.

![图片](https://user-images.githubusercontent.com/9455181/89758834-554e0d80-db1b-11ea-9ece-79456968ef3e.png)

**Comment by NUST-Machine-Intelligence-Laboratory** [comment]
Thanks for your Email.

We have moved the data from Aliyun in Hongkong to China mainland Aliyun.

Please wait one hour, we will update these links and then you can download these data from new links.

Regards,

Yazhou.
 
From: Dongliang Chang
Date: 2020-08-10 15:10
To: NUST-Machine-Intelligence-Laboratory/Softly-Update-Drop
CC: Subscribed
Subject: [NUST-Machine-Intelligence-Laboratory/Softly-Update-Drop] About datasets (#2)
Hi, the download link of the three datasets has expired, can you provide a new one? Many thanks.
